CREATE TABLE Studios (
	Id INT PRIMARY KEY,
	Name VARCHAR(MAX) NOT NULL,
	Country VARCHAR(MAX)
)
;

ALTER TABLE Movies
	ADD StudioId INT NOT NULL
;

ALTER TABLE Movies
	ADD CONSTRAINT FK_StudioId FOREIGN KEY (StudioId) REFERENCES Studios(Id)
;

-- ALTER TABLE MOVIES DROP CONSTRAINT FK_StudioId; ALTER TABLE Movies DROP COLUMN StudioId; DROP TABLE Studios
